---
title: "Prepare for the mizer course"
editor: visual
---

::: {.callout-caution}
Some of the information below is no longer important now that the live version of the course has finished.
The interaction via GitHub is no longer needed when you work through the tutorials on your own.
Instead of using the worksheets simply copy and paste the code from the tutorials to try it out and
to do the exercises.

In order for the code from the tutorials to work without problems, you should install the versions of
the mizer, mizerMR and mizerExperimental packages as they were during August 2022. To do that, follow
[these instructions](install-tools.qmd#r-packages).
:::

```{r}
#| echo: false
vembedr::embed_url("https://youtu.be/MesBEpwkTaQ") |>
    vembedr::use_align("center") |>
    vembedr::use_rounded(10)
```


While the course only starts on Monday the 8th of August, if you like you can already start preparations:

1\) You can [introduce yourself](introduce-yourself.qmd) and your interests to your fellow participants.

2\) You can [install the tools](install-tools.qmd) that we will use in the course.

3\) You can familiarise yourself with how we will be [using Git and GitHub](use-git-and-github.qmd) in this course for collaboration and feedback on your coursework.

4\) We assume that you are familiar with the basics of R programming. There are plenty of free resources to learn R. You can look through [R studio resources](https://www.rstudio.com/resources/webinars/), go through [R for Data Science](https://r4ds.had.co.nz/) or explore multiple other tools. You can also share your favourite tutorials or resources in the comments below.

That will allow for a flying start to the course. You won't believe how much we are looking forward to meeting you all on the 8th of August
