<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>mizer course - Single species spectra</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../understand/predation-growth-and-mortality.html" rel="next">
<link href="../understand/observed-size-spectra.html" rel="prev">
<link href="../images/favicon-16x16.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script><script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">
<link rel="stylesheet" href="../styles.css">
<meta name="twitter:title" content="mizer course - Single species spectra">
<meta name="twitter:description" content="At the end of the previous tutorial we plotted single-species size spectra from our dataset and observed that they were a bit of a mess.">
<meta name="twitter:creator" content="gustavdelius">
<meta name="twitter:card" content="summary">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Single species spectra</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">mizer course</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../prepare/index.html" class="sidebar-item-text sidebar-link">Prepare</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prepare/introduce-yourself.html" class="sidebar-item-text sidebar-link">Introduce yourself</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prepare/install-tools.html" class="sidebar-item-text sidebar-link">Install tools</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prepare/use-git-and-github.html" class="sidebar-item-text sidebar-link">Use Git and GitHub</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../understand/index.html" class="sidebar-item-text sidebar-link">Week 1: Understand</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../understand/observed-size-spectra.html" class="sidebar-item-text sidebar-link">Observed size spectra</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../understand/single-species-spectra.html" class="sidebar-item-text sidebar-link active">Single species spectra</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../understand/predation-growth-and-mortality.html" class="sidebar-item-text sidebar-link">Predation, growth and mortality</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../understand/species-interactions.html" class="sidebar-item-text sidebar-link">Species interactions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../understand/dynamics-of-spectra.html" class="sidebar-item-text sidebar-link">Dynamics of size spectra</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../build/index.html" class="sidebar-item-text sidebar-link">Week 2: Build</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../build/find-species-parameters.html" class="sidebar-item-text sidebar-link">Find species parameters</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../build/create-first-model.html" class="sidebar-item-text sidebar-link">Create your first model</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../build/set-multiple-resources.html" class="sidebar-item-text sidebar-link">Set up multiple resources</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../build/refine-model.html" class="sidebar-item-text sidebar-link">Refine your model</a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Week 3: Use</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  Released on 22 August
  </li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Info</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../troubleshooting.html" class="sidebar-item-text sidebar-link">Troubleshooting</a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#single-species-model" id="toc-single-species-model" class="nav-link" data-scroll-target="#single-species-model">Single-species model</a></li>
  <li><a href="#steady-state-spectrum" id="toc-steady-state-spectrum" class="nav-link" data-scroll-target="#steady-state-spectrum">Steady state spectrum</a></li>
  <li><a href="#numbers" id="toc-numbers" class="nav-link" data-scroll-target="#numbers">Numbers</a></li>
  <li><a href="#other-representations" id="toc-other-representations" class="nav-link" data-scroll-target="#other-representations">Other representations</a></li>
  <li><a href="#biomass" id="toc-biomass" class="nav-link" data-scroll-target="#biomass">Biomass</a></li>
  <li><a href="#allometric-rates" id="toc-allometric-rates" class="nav-link" data-scroll-target="#allometric-rates">Allometric rates</a></li>
  <li><a href="#slope-of-juvenile-spectrum" id="toc-slope-of-juvenile-spectrum" class="nav-link" data-scroll-target="#slope-of-juvenile-spectrum">Slope of juvenile spectrum</a></li>
  <li>
<a href="#shape-of-adult-spectrum" id="toc-shape-of-adult-spectrum" class="nav-link" data-scroll-target="#shape-of-adult-spectrum">Shape of adult spectrum</a>
  <ul class="collapse">
<li><a href="#investment-into-reproduction" id="toc-investment-into-reproduction" class="nav-link" data-scroll-target="#investment-into-reproduction">Investment into reproduction</a></li>
  <li><a href="#change-in-maturity-curve" id="toc-change-in-maturity-curve" class="nav-link" data-scroll-target="#change-in-maturity-curve">Change in maturity curve</a></li>
  <li><a href="#two-curves-in-one-plot" id="toc-two-curves-in-one-plot" class="nav-link" data-scroll-target="#two-curves-in-one-plot">Two curves in one plot</a></li>
  <li><a href="#effect-of-changed-maturity" id="toc-effect-of-changed-maturity" class="nav-link" data-scroll-target="#effect-of-changed-maturity">Effect of changed maturity</a></li>
  </ul>
</li>
  <li><a href="#summary-and-recap" id="toc-summary-and-recap" class="nav-link" data-scroll-target="#summary-and-recap">Summary and recap</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/sizespectrum/mizerCourse/edit/week-2/understand/single-species-spectra.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/sizespectrum/mizerCourse/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block">Single species spectra</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><section id="introduction" class="level2"><h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>At the end of the previous tutorial we plotted single-species size spectra from our dataset and observed that they were a bit of a mess. In this tutorial we will use the mizer model to gain an understanding of what determines the shape of a species size spectrum.</p>
<p>In this tutorial you are also going to start using mizer functions. When you want to learn more about any of the functions that we use in the examples, simply click on the function name. This will open the function’s help page in a new browser window.</p>
<p>First, load some required packages with the following commands:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-1_f18d169c770e398ad6a75b12f2594768">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">remotes</span><span class="fu">::</span><span class="fu"><a href="https://remotes.r-lib.org/reference/install_github.html">install_github</a></span><span class="op">(</span><span class="st">"sizespectrum/mizerExperimental"</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sizespectrum/mizerExperimental">mizerExperimental</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note how for the mizerExperimental package we also call <code><a href="https://remotes.r-lib.org/reference/install_github.html">remotes::install_github()</a></code>. This will reinstall the package only if it has changed on GitHub since you last installed it. If nothing has changed, the command will just issue a message to reassure you of that fact. So for packages that improve as frequently as mizerExperimental, it is always a good idea to call <code><a href="https://remotes.r-lib.org/reference/install_github.html">remotes::install_github()</a></code> frequently.</p>
<p>You will be doing your own work for this tutorial in the accompanying worksheet file “worksheet2-single-species-spectra.Rmd”. You will find this file in the worksheet repository for this week that you already used during the previous tutorial.</p>
</section><section id="single-species-model" class="level2"><h2 class="anchored" data-anchor-id="single-species-model">Single-species model</h2>
<p>In this and the next tutorial we want to keep the size-spectrum aspects of the mizer model separate from the multi-species aspects, in order to not have to think about too many things at once. So we will explore a model where a single species lives in a non-dynamical background community that we will set to a Sheldon power-law abundance. Only in the fourth tutorial of this week exploring <a href="../understand/species-interactions.html">species interactions</a> will we start to consider the interesting multi-species phenomena that arise in mizer models.</p>
<p>In this tutorial we will only be interested in the shape of the size spectrum, i.e., in how the total number of individuals is distributed over the different sizes. We are not yet interested in the overall abundance of the species. The overall abundance would be influenced by the total rate of reproduction and recruitment for the species. This in turn would be influenced by the size spectrum, because that determines how many of the individuals are mature. This dynamic feedback will of course become important when we build real-world models in week 2 and use them in week 3. But for now we have enough on our plate without thinking also about this.</p>
<p>Mizer collects all the parameters describing a size-spectrum model into one object of class <code>MizerParams</code>. You do not need to set up this object by hand but instead there are several wrapper functions in mizer that create the object for you for various types of models, and also many functions for changing specific parameters in a model. We will use the <code><a href="https://sizespectrum.org/mizer/reference/newSingleSpeciesParams.html">newSingleSpeciesParams()</a></code> function to set up a model describing a single fish species living in an ecosystem whose community size spectrum is given by a power-law.</p>
<p>The <code><a href="https://sizespectrum.org/mizer/reference/newSingleSpeciesParams.html">newSingleSpeciesParams()</a></code> function has many arguments that allow you to specify parameters for the fish species as well as for the community, but all these arguments have default values, so we can simply call the function without specifying those arguments. We will only specify the power-law exponent <code>lambda</code> of the background community. Note that in mizer the size spectrum exponent refers to the number density on a linear weight axis x and is therefore expected to be around 2.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-2_71dfe2feab32ef79c6eb232dd8499e54">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">params</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/newSingleSpeciesParams.html">newSingleSpeciesParams</a></span><span class="op">(</span>lambda <span class="op">=</span> <span class="fl">2.05</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function returns a <code>MizerParams</code> object and we have assigned that to the variable <code>params</code>. We will be explaining more about this model as we go along.</p>
</section><section id="steady-state-spectrum" class="level2"><h2 class="anchored" data-anchor-id="steady-state-spectrum">Steady state spectrum</h2>
<p>As a final simplification in this and the next two tutorials, we will only consider the steady state size spectra. The steady state is the state where in each size class the inflow of individuals through growth exactly balances the outflow of individuals through growth and death. This means that the size spectrum is in equilibrium. You might have heard that models are often “initialised” from some initial species abundances and then ran to equilibrium until species biomasses and size distributions stop changing. However, we can calculate what sort of initial abundance we need to ensure that a species is in an equilibrium and this is what mizer does. The initial size spectra in the <code>params</code> object that we created with <code><a href="https://sizespectrum.org/mizer/reference/newSingleSpeciesParams.html">newSingleSpeciesParams()</a></code> have already been set to the steady state size spectra.</p>
<p>We can plot the size spectrum with the <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code> function.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-3_eef0e92e18b1efa42397b547689879d5">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra</a></span><span class="op">(</span><span class="va">params</span>, power <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <code>power = 0</code> argument to the <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code> function specifies that we want to plot the number density, rather than for example the biomass density. We’ll discuss this more below in the section on <a href="#other-representations">other representations</a>.</p>
<p>The green line represents the number density of the background community, labelled as “Resource” in the plot legend, in which our foreground species finds itself. The green line is a straight line with slope <code>lambda = -2.05</code>. Thus the number density of the background community is proportional to <span class="math inline">w^{-2.05}</span>. It is important to understand that a power-law curve looks like a straight line when plotted on logarithmic axes and the slope of the line is the exponent in the power law. If this does not sound familiar, please revisit the section in the previous tutorial where we <a href="observed-size-spectra.qmdfitting-a-power-law">fitted a power-law</a> to the community spectrum.</p>
<p>The other line represents the number density of our single species, which by default is just named unimaginatively “Target species”. We see that it is a straight line initially, but then has a bump before declining rapidly at large sizes. We will discuss in a short while what causes that shape.</p>
<p>Remember what these size spectra plots indicate? They show the number density of individuals as a function of size. The initial slope of the target species’ number density is negative, which vaguely means that there are fewer larger fish than smaller fish. That is of course understandable: lots of fish die while they are growing up, so there tend to be fewer fish in larger size classes.</p>
<p>It is now time to do the first exercise of this tutorial. To complete the exercise, go to your copy of this week’s worksheet repository and open the file “worksheet2-single-species-spectra.Rmd” in RStudio. There you will find the following first exercise:</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Create a MizerParams object describing a single species in a power-law background where the Sheldon exponent is 2.1. Then plot the number density as a function of weight.</p>
</div>
</div>
</div>
</section><section id="numbers" class="level2"><h2 class="anchored" data-anchor-id="numbers">Numbers</h2>
<p>While the <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code> function gives us a plot of the number density, it would be nice if we could get at the actual numerical values. We can access them with the <code><a href="https://sizespectrum.org/mizer/reference/initialN-set.html">initialN()</a></code> function. Let us assign this to a variable <code>n</code>:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-4_49e6a423896e2bbdc8528a922293cbe8">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/initialN-set.html">initialN</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see in the “Environment” pane in RStudio, <code>n</code> is a matrix with 1 row and 101 columns. The one row corresponds to the one species. In a multispecies model there would be one row for each species, holding the number density for that species. The 101 columns are for the number densities in each of the 101 size classes. By default mizer uses 100+1 size clases (or size bins), although you can easily change that. In fact, <code>n</code> is a named array, i.e., each row and each column has names. These we can extract with the <code><a href="https://rdrr.io/r/base/dimnames.html">dimnames()</a></code> function.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-5_72507a085f4ce2571269ac9ff7ba5404">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$sp
[1] "Target species"

$w
  [1] "0.001"   "0.00112" "0.00126" "0.00141" "0.00158" "0.00178" "0.002"  
  [8] "0.00224" "0.00251" "0.00282" "0.00316" "0.00355" "0.00398" "0.00447"
 [15] "0.00501" "0.00562" "0.00631" "0.00708" "0.00794" "0.00891" "0.01"   
 [22] "0.0112"  "0.0126"  "0.0141"  "0.0158"  "0.0178"  "0.02"    "0.0224" 
 [29] "0.0251"  "0.0282"  "0.0316"  "0.0355"  "0.0398"  "0.0447"  "0.0501" 
 [36] "0.0562"  "0.0631"  "0.0708"  "0.0794"  "0.0891"  "0.1"     "0.112"  
 [43] "0.126"   "0.141"   "0.158"   "0.178"   "0.2"     "0.224"   "0.251"  
 [50] "0.282"   "0.316"   "0.355"   "0.398"   "0.447"   "0.501"   "0.562"  
 [57] "0.631"   "0.708"   "0.794"   "0.891"   "1"       "1.12"    "1.26"   
 [64] "1.41"    "1.58"    "1.78"    "2"       "2.24"    "2.51"    "2.82"   
 [71] "3.16"    "3.55"    "3.98"    "4.47"    "5.01"    "5.62"    "6.31"   
 [78] "7.08"    "7.94"    "8.91"    "10"      "11.2"    "12.6"    "14.1"   
 [85] "15.8"    "17.8"    "20"      "22.4"    "25.1"    "28.2"    "31.6"   
 [92] "35.5"    "39.8"    "44.7"    "50.1"    "56.2"    "63.1"    "70.8"   
 [99] "79.4"    "89.1"    "100"    </code></pre>
</div>
</div>
<p>The names of the columns are the weight in grams at the start of each size class. Notice how R displays long vectors by breaking them across many lines and starting each line with a number in brackets. That number is the index of the first value in that row. So for example we see that the 61st size class starts at 1 gram. The number density in the size class between 1 gram and 1.12 grams (the start of the next size class) is</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-6_2c9f18af2ddfaf487fddf5f36b89ba9e">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">61</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003282314</code></pre>
</div>
</div>
<p>It is important to realise that this is not the number of fish in the size class, but the average number density in the size class. To get the number of fish we have to multiply the number density by the width of the size class. Those widths can be obtained with the <code><a href="https://sizespectrum.org/mizer/reference/w.html">dw()</a></code> function. So the number of fish in each size class is obtained with</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-7_8368e64ca4161eacbbddeb9e4acafa2c">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">numbers</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">*</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/w.html">dw</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The number of individuals in the size class between 1 gram and 1.12 grams is</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-8_2be458055deaebadee88149edbe7cb51">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">numbers</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">61</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.005029e-05</code></pre>
</div>
</div>
<p>You may be surprised by the small number if you interpret it as the number of fish between 1 gram and 1.12 gram in the entire ocean. However it looks more reasonable if it is the average number per square meter of sea. For more of a discussion of this issue of working with numbers per area, numbers per volume or numbers for the entire system see <a href="https://sizespectrum.org/mizer/reference/setParams.html#units-in-mizer" class="uri">https://sizespectrum.org/mizer/reference/setParams.html#units-in-mizer</a></p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Determine the total number of fish in the model with sizes between 10 grams and 20 grams. You can use the <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> function to add together contributions from the various size classes.</p>
</div>
</div>
</div>
<p>Again, you should complete this exercise in the worksheet in which you already completed exercise 1.</p>
</section><section id="other-representations" class="level2"><h2 class="anchored" data-anchor-id="other-representations">Other representations</h2>
<p>We have seen in the previous tutorial on <a href="../understand/observed-size-spectra.html">observed size spectra</a> that the size spectrum can be represented in various ways. Besides the number density <span class="math inline">N(w)</span> we introduced the biomass density <span class="math inline">B(w)</span>, the number density in log weight <span class="math inline">N_{\log}(w)</span> and the biomass density in log weight <span class="math inline">B_{\log}(w)</span>. These were related to each other by multiplication by different powers of <span class="math inline">w</span>:</p>
<p><span class="math display">B(w) = N_{\log}(w) = w N(w) \text{ and } B_{\log}(w) = w^2 N(w).</span></p>
<p>We can use the <code>power</code> argument of the <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code> function to determine which of these densities to plot. Above we plotted the number density by setting <code>power = 0</code>. Without the <code>power</code> argument (or with <code>power = 1</code> which is the default) the <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code> function plots the biomass density as a function of weight, which is also the number density as a function of log weight:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-9_671a070fdd0481975c3ccc839d5bd828">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now the green line representing the biomass density of the background has a slope of -1.05 and not the -2.05 number density slope that we actually set when creating the params object.</p>
<p>The initial slope of the species biomass density is also negative, meaning that the biomass density in the species decreases with size.</p>
<p>We can also plot the biomass density in log weight, i.e., the Sheldon spectrum, by supplying the argument <code>power = 2</code> to <code><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra()</a></code>.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-10_ead0bfb3fa406d0765cb51c67b13609a">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra</a></span><span class="op">(</span><span class="va">params</span>, power <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This now shows an approximately constant background biomass density in log weight (the slope of the green line is -0.05). The biomass density of the species in log size initially increases. So if binned in logarithmically-sized bins the biomass in each bin will initially increase, until it starts decreasing close to the maximum size of the species.</p>
<p>This latest plot seems to indicate that most of the biomass of the species is concentrated at larger sizes of around 30 grams, whereas the previous plot seemed to indicate that most of the biomass is at the smallest sizes. So which one is true? Please think about this question, because it really highlights the importance of not confusing biomass density with biomass. Questions about the amount of biomass <strong>at a size</strong> do not make sense. Instead you have to ask about biomass <strong>in a size range</strong>.</p>
<p>So for example, we might want to consider the prey biomass available to two different predators of our species, one small and one large. Assume that the smaller predator feeds on prey in the size range from 1g to 2g. The other predator, which we assume is 10 times larger, feeds on prey in the size range from 10g to 20g. These feeding intervals have the same width on the logarithmic weight axis. Therefore we should look at the plot of the biomass density in log weight to see that the larger predator has a lot more prey biomass from our species available to it than the smaller one. This is in spite of the fact that the plot of biomass density in weight tells us that the biomass density is lower at 10g than at 1g.</p>
<p>It may have been a bit confusing that we displayed the same size spectrum in three different ways. But it is important to be aware of this because in the literature you will see all different conventions being used, so if you see a plot of a size spectrum you always need to ask yourself exactly which density is being shown.</p>
</section><section id="biomass" class="level2"><h2 class="anchored" data-anchor-id="biomass">Biomass</h2>
<p>As we did for <a href="#numbers">numbers</a> above, let us also look at how to extract biomasses from the model.</p>
<p>We already said above that we can obtain the biomass density in a size class from the number density by multiplying the number density by the weight of the individuals in the size class. To obtain the appropriate weights, we use the function <code><a href="https://sizespectrum.org/mizer/reference/w.html">w()</a></code> that returns the weights at the start of each size class. So we calculate</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-11_0796fec84bd46ffb1bb6bb6b771afd74">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">biomass_density</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">*</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/w.html">w</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We obtain the total biomass in each size class by multiplying the biomass density in each size class by the width of each size class</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-12_3c250d713ba0d879fcb88679b2d4d1ba">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">biomass</span> <span class="op">&lt;-</span> <span class="va">biomass_density</span> <span class="op">*</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/w.html">dw</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For example the biomass of fish between 1 gram and 1.12 grams is</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-13_bab22158b932195de52de73e2964659e">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">biomass</span><span class="op">[</span><span class="fl">61</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.005029e-05</code></pre>
</div>
</div>
<p>Let us briefly present yet another way to represent the size distribution. When we talk about size spectra, we always have the representation in terms of densities in mind. You may already be familiar with the concept of a densities from probability theory, where you can describe a probability distribution in terms of its probability density function. But perhaps you also know that there is an alternative description of the probability distribution in terms of the cumulative distribution function. We can similarly describe the size distribution of the biomass by a cumulative biomass distribution function, which gives the total biomass of all sizes up to a specific size.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-14_53b1d486c305585469d1ac61408e192f">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Initialise an array with the right dimensions</span></span>
<span><span class="va">cumulative_biomass</span> <span class="op">&lt;-</span> <span class="va">biomass</span></span>
<span><span class="co"># Calculate the cumulative sum of all biomasses in previous bins</span></span>
<span><span class="va">cumulative_biomass</span><span class="op">[</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">biomass</span><span class="op">)</span></span>
<span><span class="co"># Normalise this so that it is given as a percentage of the total biomass</span></span>
<span><span class="va">cdf</span> <span class="op">&lt;-</span> <span class="va">cumulative_biomass</span> <span class="op">/</span> <span class="va">cumulative_biomass</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">101</span><span class="op">]</span> <span class="op">*</span> <span class="fl">100</span></span>
<span><span class="co"># Melt the array to a data frame and then plot</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">cdf</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Weight [g]"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"% of total biomass"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot shows us for example that 50% of the individuals are smaller than 12.5g and only a very small percentage is larger than 75g.</p>
<p>The biomass density is the slope of this graph. We can also plot the cumulative biomass distribution function on a logarithmic weight axis:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-15_62f15ce40d1fc1b9f0d612c82246c119">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">cdf</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Weight [g]"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"% of total biomass"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_log10</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This graph contains exactly the same information as the previous graph, just showing more detail at smaller sizes and less detail at larger sizes. We can see for example that about 20% of individuals are less than 1g, which was difficult to see in the previous graph. The slope of this graph is the biomass density in log weight.</p>
</section><section id="allometric-rates" class="level2"><h2 class="anchored" data-anchor-id="allometric-rates">Allometric rates</h2>
<p>The first striking feature of the species size-spectrum, independently of which density you plot, is that for small fish (larvae and juveniles) it is given by a straight line. This is due to the allometric scaling of the physiological rates that our model is assuming and which we will discuss in this section. The other striking feature is the bulge at around maturity size, which we will discuss in the section on the <a href="#shape-of-adult-spectrum">shape of the adult spectrum</a>.</p>
<p>We will assume that the metabolic rate, i.e., the rate at which an organism expends energy on its basic metabolic needs, scales as a power of the organism’s body size, and the power is about <span class="math inline">p = 3/4</span>.</p>
<p>Because this energy needs to be supplied by consumption of food, it is natural to assume that also the consumption rate scales allometrically with a power of <span class="math inline">n = 3/4</span>. When the consumption is greater than the metabolic cost then the excess leads to growth. Hence the growth rate too scales allometrically with power <span class="math inline">3/4</span>.</p>
<p>In a multi-species mizer model the mortality is an emergent property that depends on the abundance of predators. In this single species model the mortality rate is set to the one that would emerge if all the species in the fixed background community predated with the same ferocity as the target species. This leads to a mortality rate that scale allometrically with a power of <span class="math inline">n - 1 = 3/4 - 1 = -1/4</span>. This means that the death rate experienced by larger individuals is smaller than that of small individuals.</p>
<p>It is a result of the mathematics that if the growth and death rates scale allometrically with exponents <span class="math inline">p</span> and <span class="math inline">1-p</span> respectively, for some metabolic exponent <span class="math inline">p</span>, that the number density at steady state is also a power law, i.e., a straight line on the log-log plot.</p>
<p>Let us check that in our model the physiological rates are indeed power laws, at least for the small sizes. We can get the growth rate with the <code><a href="https://sizespectrum.org/mizer/reference/getEGrowth.html">getEGrowth()</a></code> function. We assign the result to a variable that we name <code>growth_rate</code>.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-16_d517c7059b3e93c4ffc273ad0834c09c">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">growth_rate</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/getEGrowth.html">getEGrowth</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can again see in the “Environment” pane that this is a matrix with one row for the one species and 101 columns for the 101 size classes. So for example the growth rate at size 1 gram is</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-17_6c21334c4669bf344e8293f290305d19">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">growth_rate</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">61</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.26968</code></pre>
</div>
</div>
<p>(because we had seen that the 61st size class starts at 1 gram). This is the instantaneous per-capita growth rate, measured in grams per year. Note that in mizer all rates are measured in units of year, but for many people daily values are easier to understand. Since growth rate here is an instantaneous rate we can simply divide it by 365 to get a daily rate (although note that mizer does not simulate processes on daily time steps). This gives us a growth rate per day for a 1g sized fish of</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-18_151b4e9dd9579237ebaf684ef047fe14">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">growth_rate</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">61</span><span class="op">]</span> <span class="op">/</span> <span class="fl">365</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02265666</code></pre>
</div>
</div>
<p>We would like to make a log-log plot of the growth rate against size to check that it gives a straight line. We will use <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> for that purpose. <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> likes to work with data frames instead of named matrices, so we first convert the matrix into a data frame with the <code><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt()</a></code> function.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-19_3a0a007a89453a9188eadf61c0ba60b8">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">growth_rate_frame</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">growth_rate</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can see in the “Environment” pane that the new variable that we called <code>growth_rate_frame</code> is a data frame with 101 observations of 3 variables. The 101 observations correspond to the 101 size classes. The 3 variables have names</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-20_a028902827ade13521b5b3edb964a2bc">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">growth_rate_frame</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sp"    "w"     "value"</code></pre>
</div>
</div>
<p>They are the species <code>sp</code>, the size <code>w</code>, and the <code>value</code> which contains the growth_rate. This data frame we can pass to <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code>.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-21_413a47139da4cd9f27e42b2c68e92538">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">growth_rate_frame</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_log10</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Weight [g]"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_log10</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Growth rate [g/year]"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note how we linked the x axis to the <code>w</code> variable and the y axis to the <code>value</code> variable and specified that both axes should be on a logarithmic scale.</p>
<p>We see that at least up to a size of a few grams the line is straight. Let’s isolate the growth rate for those smaller sizes</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-22_b3116765d29b85984caf03155e840b86">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">g_small_fish</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">growth_rate_frame</span>, <span class="va">w</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and fit a linear model</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-23_9b0fdde202229a4a44a37c7395526f55">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">g_small_fish</span><span class="op">$</span><span class="va">value</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">g_small_fish</span><span class="op">$</span><span class="va">w</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(g_small_fish$value) ~ log(g_small_fish$w))

Coefficients:
        (Intercept)  log(g_small_fish$w)  
              2.113                0.750  </code></pre>
</div>
</div>
<p>The slope of the line is indeed <span class="math inline">0.75 = 3/4</span>. In fact, the above shows that for juveniles <span class="math display">\log(g(w)) = 2.113 + \frac34 \log(w)</span> and thus <span class="math display">g(w) = g_0\ w^p = \exp(2.113)\  w^{3/4}.</span></p>
<p>Of course in a real model, the growth rate would not so exactly follow a power law, because growth rate would vary depending on food availability, for example. In this example food is the background resource and its abundance is fixed, so food abundance does not vary.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Use the methods you have just seen to make a log-log plot of the mortality rate. You can get the mortality rate with the <code><a href="https://sizespectrum.org/mizer/reference/getMort.html">getMort()</a></code> function. While adjusting the code to this new task, you need to take into account that the name of the size-dimension of the array returned by <code><a href="https://sizespectrum.org/mizer/reference/getMort.html">getMort()</a></code> is <code>"w_prey"</code> instead of <code>"w"</code>.</p>
<p>Then fit a linear model to determine the slope and and intercept and thus the allometric exponent <span class="math inline">r</span> and the coefficient <span class="math inline">\mu_0</span> for the mortality rate <span class="math display">\mu(w) = \mu_0 w^r.</span></p>
</div>
</div>
</div>
</section><section id="slope-of-juvenile-spectrum" class="level2"><h2 class="anchored" data-anchor-id="slope-of-juvenile-spectrum">Slope of juvenile spectrum</h2>
<p>We have seen that for juvenile fish the growth rate and the death rate are both power laws with exponents <span class="math inline">p=3/4</span> and <span class="math inline">r=p-1=-1/4</span> respectively. By solving a differential equation we can derive that the juvenile spectrum also follows a power law: <span class="math display">N(w) = N_0\ w^{-\mu_0/g_0 - p}</span></p>
<p>I won’t do the maths here with you (and you probably don’t want me to anyway), but we can see that the result makes sense. It tells us that the number density drops of faster with size if the mortality rate coefficient <span class="math inline">\mu_0</span> is higher or if the growth rate coefficient <span class="math inline">g_0</span> is smaller, which is what we would expect.</p>
<p>We can also check this claim numerically. Let’s look at the spectrum of individuals up to 10 grams. By now we know how to do this. We first convert the number density matrix <code>n</code> into a dataframe and then filter out all observations that do not have <span class="math inline">w\leq 10</span>. The resulting data frame we pass to <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> and ask it to plot a line on log-log axes.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-26_c8386b13fb2f8fd4734c7893711cc80f">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">w</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">nf</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_log10</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Weight [g]"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_log10</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Number density [1/g]"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That confirms what we had seen earlier, that for fish less than 10 grams the number density is a power law. To determine the exponent of the power law we need the slope of that straight line in the log-log plot, and the easiest way to do that is to fit a linear model to the log variables:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-27_7013a917cc09877ec9eeb0c23bcdad83">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">nf</span><span class="op">$</span><span class="va">value</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">nf</span><span class="op">$</span><span class="va">w</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(nf$value) ~ log(nf$w))

Coefficients:
(Intercept)    log(nf$w)  
     -8.022       -1.682  </code></pre>
</div>
</div>
<p>The linear model fit says that the exponent is -1.682. The mathematics claimed that the exponent should be <span class="math inline">-\mu_0 / g_0 - p</span>. We have already observed that <span class="math inline">\mu_0 = 2.038</span> and <span class="math inline">g_0 = 2.113</span> so we get</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-29_c98e7b2033c0834aff4d7c5a8b1bc417">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">-</span><span class="va">m0</span> <span class="op">/</span> <span class="va">g0</span> <span class="op">-</span> <span class="fl">3</span><span class="op">/</span><span class="fl">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.714505</code></pre>
</div>
</div>
<p>That is not quite the result of the linear model fit, but that is the nature of numerical calculations: one gets discretisation errors and rounding errors. Anyway it is close enough. And it is also amazing how we can calculate expected numbers of fish from basic assumptions and rules. Of course natural ecosystems never look like that, but if we have theoretical expectations derived from clear assumptions (about growth and mortality rate and food availability), we can start asking questions about which processes in natural ecosystems deviate from these generic assumptions, why this happens and how it should affect the observed size spectra.</p>
</section><section id="shape-of-adult-spectrum" class="level2"><h2 class="anchored" data-anchor-id="shape-of-adult-spectrum">Shape of adult spectrum</h2>
<p>Now that we understand the shape of the size spectrum for the juvenile fish, let us try to understand the shape of the adult spectrum. Here is the plot of the biomass density again, but with the <span class="math inline">w</span> axis restricted to weights above 10g:</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-30_ac1f0081b00fb74e7f574a0ea0f08911">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/plotSpectra.html">plotSpectra</a></span><span class="op">(</span><span class="va">params</span>, wlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The increase of abundance that we see at around the maturity size of our species is due to a drop in growth rate at that size. This in turn is due to the fact that the mature fish invests some of its energy into reproduction. So the details of the shape of the adult spectrum will be influenced both by food intake, maintenance and mortality (like in juveniles), but also by how adults split their energy income between growth and reproduction.</p>
<section id="investment-into-reproduction" class="level3"><h3 class="anchored" data-anchor-id="investment-into-reproduction">Investment into reproduction</h3>
<p>Let us look at a plot of the proportion of the available energy that is invested into reproduction as a function of the size. This is the product of the proportion of individuals that are mature (obtained with the function <code><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">maturity()</a></code> and the proportion of their energy income that a mature fish invests into reproduction (obtained with the function <code><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">repro_prop()</a></code>.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-31_96227428021b856a56fbf898a40ac43f">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reprod_proportion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">maturity</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">repro_prop</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span>
<span><span class="co"># Convert the array to a data frame for ggplot</span></span>
<span><span class="va">psi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="va">reprod_proportion</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">psi</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Weight [g]"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Proportion invested into reproduction"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>How was this maturity curve specified? You can find the details in the <a href="https://sizespectrum.org/mizer/reference/setReproduction.html#investment">mizer documentation</a>. There are four species parameters involved:</p>
<ul>
<li>the maturity size <code>w_mat</code> at which 50% of the individuals are mature.</li>
<li>the size <code>w_mat25</code> at which 25% of the individuals are mature.</li>
<li>the asymptotic size <code>w_inf</code> at which an organism invests 100% of its income into reproduction and thus growth is zero.</li>
<li>an exponent <code>m</code> that determines how the proportion that an individual invests into reproduction scales with its size.</li>
</ul>
<p>Such species parameters are contained in a data frame inside the <code>params</code> object that we can access with the <code><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params()</a></code> function.</p>
<div class="cell" data-df-print="tibble" data-hash="single-species-spectra_cache/html/unnamed-chunk-32_ce9994330431b7b012e6214a0a7fb360">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      species w_min w_inf    w_mat w_min_idx k_vb    gamma
Target species Target species 0.001   100 25.11886         1    1 4067.903
                     ks  f0   fc beta sigma z0 alpha   erepro
Target species 5.906914 0.6 0.25  100   1.3  0   0.4 0.899483
               interaction_resource    n    p   q pred_kernel_type        h k
Target species                    1 0.75 0.75 0.8        lognormal 59.06914 0
                w_mat25 m R_max
Target species 22.50546 1   Inf</code></pre>
</div>
</div>
<p>As you can see, there are a lot of other species parameters, some of which we will talk about later. For now let’s just select the 4 parameters we are interested in.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-33_ea022f4d2e13e18370a45b6f034a215f">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span>, <span class="va">w_mat</span>, <span class="va">w_mat25</span>, <span class="va">w_inf</span>, <span class="va">m</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  w_mat  w_mat25 w_inf m
Target species 25.11886 22.50546   100 1</code></pre>
</div>
</div>
<p>And with this knowledge of parameter we can improve the plot for clarity and add a vertical line at 25% and 50% maturation weight</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-34_5a506e7b7cb2dc7391d3ce6307fe7a77">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">maturation_weight50</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat</span></span>
<span><span class="va">maturation_weight25</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat25</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">maturation_weight50</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">maturation_weight25</span>, lty <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="change-in-maturity-curve" class="level3"><h3 class="anchored" data-anchor-id="change-in-maturity-curve">Change in maturity curve</h3>
<p>Let us investigate what happens when we change the maturity curve. Let’s assume the maturity size is actually 40 grams and the size at which 25% of individuals is mature is 30 grams. Let us change the values in the <code>species_params</code> data frame. But first we make a copy of the params object so that we can keep the old version around unchanged.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-35_67c09c5c85e10c92843f826a0ab119ff">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">params_changed_maturity</span> <span class="op">&lt;-</span> <span class="va">params</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this copy we now change the species parameters</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-36_1bdc9c6db400348305f1787b8188bf17">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat</span> <span class="op">&lt;-</span> <span class="fl">40</span></span>
<span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat25</span> <span class="op">&lt;-</span> <span class="fl">30</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span>, <span class="va">w_mat</span>, <span class="va">w_mat25</span>, <span class="va">w_inf</span>, <span class="va">m</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               w_mat w_mat25 w_inf m
Target species    40      30   100 1</code></pre>
</div>
</div>
<p>Now the maturity curve has changed, which we can verify by plotting it</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-37_00092450259a5e33266648de7600f885">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">psi_changed_maturity</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/reshape2/man/melt.html">melt</a></span><span class="op">(</span><span class="fu"><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">maturity</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span> <span class="op">*</span> </span>
<span>                                 <span class="fu"><a href="https://sizespectrum.org/mizer/reference/setReproduction.html">repro_prop</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">psi_changed_maturity</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat</span>, </span>
<span>               lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://sizespectrum.org/mizer/reference/species_params.html">species_params</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span><span class="op">$</span><span class="va">w_mat25</span>, </span>
<span>               lty <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Weight [g]"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Proportion invested into reproduction"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="two-curves-in-one-plot" class="level3"><h3 class="anchored" data-anchor-id="two-curves-in-one-plot">Two curves in one plot</h3>
<p>At this point let’s take a little break and learn how to draw two curves in the same graph. How can we see the old maturity curve and the new maturity curve in the same plot? First we add an extra column to each dataframe describing it</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-38_f7948efc2ad580325c555f67c5d969b2">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">psi</span><span class="op">$</span><span class="va">type</span> <span class="op">=</span> <span class="st">"original"</span></span>
<span><span class="va">psi_changed_maturity</span><span class="op">$</span><span class="va">type</span> <span class="op">=</span> <span class="st">"changed"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we bind the two data frames together</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-39_a0a43730decb0ca9a83095fc5e0654dd">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">psi_combined</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">psi</span>, <span class="va">psi_changed_maturity</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and send that combined data frame to <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code></p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-40_4d9b4a35ce59f7274439577a29f3c98a">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">psi_combined</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">w</span>, y <span class="op">=</span> <span class="va">value</span>, colour <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Weight [g]"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Proportion invested into reproduction"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This change in the maturity curve of course implies a change in the growth rates.</p>
<div class="callout-caution callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Exercise 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Make a plot showing the growth rates of the original model and of the model with the changed maturity curve.</p>
</div>
</div>
</div>
</section><section id="effect-of-changed-maturity" class="level3"><h3 class="anchored" data-anchor-id="effect-of-changed-maturity">Effect of changed maturity</h3>
<p>Next let us look at how the change in the maturity parameters affects the steady state spectrum. First need to calculate the new steady state using the function <code><a href="https://rdrr.io/pkg/mizerExperimental/man/singleSpeciesSteady.html">singleSpeciesSteady()</a></code>.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-41_51fb5f0c9c8cc14d246a25786b952d01">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">params_changed_maturity</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mizerExperimental/man/singleSpeciesSteady.html">singleSpeciesSteady</a></span><span class="op">(</span><span class="va">params_changed_maturity</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we can use the function <code><a href="https://rdrr.io/pkg/mizerExperimental/man/plotSpectra2.html">plotSpectra2()</a></code> to plot the old size spectrum and the new size spectrum on the same graph.</p>
<div class="cell" data-hash="single-species-spectra_cache/html/unnamed-chunk-42_bc48ce6a80e7c7917e333c60e25248a6">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/mizerExperimental/man/plotSpectra2.html">plotSpectra2</a></span><span class="op">(</span><span class="va">params</span>, <span class="st">"Early maturity"</span>,</span>
<span>             <span class="va">params_changed_maturity</span>, <span class="st">"Late maturity"</span>,</span>
<span>             power <span class="op">=</span> <span class="fl">2</span>, resource <span class="op">=</span> <span class="cn">FALSE</span>, wlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="single-species-spectra_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As expected, the bump happens later due to the larger maturity size and it is less pronounced, because the maturity curve is less steep. This means that fish do not suddenly start investing most of their energy into reproduction, but still keep growing while they are maturity. Since they are still growing they will be moving from one size class to another and fewer individuals will accumulate in one size class.</p>
<p>This was our first investigation of how the shape of a species size spectrum changes as model parameters are changed. We will do much more in this direction in the next tutorial in which we discuss how growth and mortality are determined through predation.</p>
</section></section><section id="summary-and-recap" class="level2"><h2 class="anchored" data-anchor-id="summary-and-recap">Summary and recap</h2>
<p>1) The steady state is the state where the system has reached an equilibrium in which the rate at which individuals grow into each size class is equal to the rate at which individuals either grow out of the size class or die in the size class.</p>
<p>2) Mizer stores the size spectrum in the form of the number density in size classes. To get the numbers in a size class we need to multiply the number density by the width of the size class (dw). To get total biomass in each size class we further multiple this value by the weight of this size class (w).</p>
<p>3) Allometric scaling of physiological rates with size plays a big role in a mizer model and shapes the size spectrum.</p>
<p>4) We studied a single species living in a fixed background community with a power-law spectrum. In this simple case we can determine the steady state spectrum and find that the juvenile spectrum is given by a power law whose exponent is determined by the ratio of mortality to growth and is different from the community spectrum power law.</p>
<p>5) As fish mature they start investing some of their energy into reproduction and hence their growth slows. This leads to a bump in the size spectrum. We saw how changes in the parameters describing the maturity ogive change the shape of that bump.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/https:\/\/course\.mizer\.sizespectrum\.org/);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script><script src="https://giscus.app/client.js" data-repo="sizespectrum/mizerCourse" data-repo-id="R_kgDOHlJwYg" data-category="Comments" data-category-id="DIC_kwDOHlJwYs4CP_7j" data-mapping="title" data-reactions-enabled="0" data-emit-metadata="0" data-input-position="bottom" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../understand/observed-size-spectra.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Observed size spectra</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../understand/predation-growth-and-mortality.html" class="pagination-link">
        <span class="nav-page-text">Predation, growth and mortality</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>